name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code..
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Tests
      - name: Run tests
        run: |
          pytest

      # Step 5: Set up Docker Buildx (for cross-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 6: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ezio_rag_app .

      # Step 7: Scan Docker image with Trivy
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@v0  # Use latest stable Trivy version
        with:
          image-ref: ezio_rag_app
          format: table
          severity: HIGH,CRITICAL


      # Step 8: Push to Docker Hub (optional)
      # Uncomment the following section if you want to push to Docker Hub
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Push Docker image to Docker Hub
      #   run: |
      #     docker tag ezio_rag_app yourdockerhubusername/ezio_rag_app:latest
      #     docker push yourdockerhubusername/ezio_rag_app:latest
